<a href="https://colab.research.google.com/github/Znixz/haidezlair/blob/main/GenAI_engr/Python_for_Data_Science_AI_%26_Development/my_python_class/IBM_Notes/IBM_panda_practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Hands-on Lab: Loading data with Pandas

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Use Pandas to access and view data

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#About-the-Dataset">About the Dataset</a></li>
        <li><a href="#Introduction-of-Pandas">Introduction of <code>Pandas</code></a></li>
        <li><a href="#Viewing-Data-and-Accessing-Data">Viewing Data and Accessing Data</a></li>
        <li><a href="#Quiz-on-DataFrame">Quiz on DataFrame</a></li>
    </ul>

</div>

<hr>

## About the Dataset

The table has one row for each album and several columns.

<ul>
    <li><b>artist</b>: Name of the artist</li>
    <li><b>album</b>: Name of the album</li>
    <li><b>released_year</b>: Year the album was released</li>
    <li><b>length_min_sec</b>: Length of the album (hours,minutes,seconds)</li>
    <li><b>genre</b>: Genre of the album</li>
    <li><b>music_recording_sales_millions</b>: Music recording sales (millions in USD) on <a href="http://www.song-database.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">[SONG://DATABASE]</a></li>
    <li><b>claimed_sales_millions</b>: Album's claimed sales (millions in USD) on <a href="http://www.song-database.com/">[SONG://DATABASE]</a></li>
    <li><b>date_released</b>: Date on which the album was released</li>
    <li><b>soundtrack</b>: Indicates if the album is the movie soundtrack (Y) or (N)</li>
    <li><b>rating_of_friends</b>: Indicates the rating from your friends from 1 to 10</li>
</ul>

You can see the dataset here:

<font size="1">
<table font-size:xx-small>
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th>
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td>
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td>
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td>
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td>
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td>
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td>
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td>
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td>
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

## Introduction of <code>Pandas</code>

In [4]:
# Dependency needed to install file

# If running the notebook on your machine, else leave it commented
!pip install xlrd
!pip install openpyxl

#import piplite
#await piplite.install(['xlrd','openpyxl'])

Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [7]:
# Import required library

import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (<b>.csv</b>) file to a dataframe. This variable <code>csv_path</code> stores the path of the <b>.csv</b>, that is  used as an argument to the <code>read_csv</code> function. The result is stored in the object <code>df</code>, this is a common short form used for a variable referring to a Pandas dataframe.

In [32]:
# Read data from CSV file

csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)
df
#df.index     # gives rows labels
#df.columns   # gives columns labels
#df.shape     # gives the number of (rows , columns)
#df.shape[0]  # gives number of rows
#df.shape[1]  # gives number of columns
#df.head()    # takes head(n) of  first nth rows to print otherwise print first five
#df.info()    # gives a quick summary of the data contents

#from pyodide.http import pyfetch
#import pandas as pd

#filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"

#async def download(url, filename):
#    response = await pyfetch(url)
#    if response.status == 200:
#        with open(filename, "wb") as f:
#            f.write(await response.bytes())


#await download(filename, "TopSellingAlbums.csv")
#df = pd.read_csv("TopSellingAlbums.csv")

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

> Note: This version of the lab is working on JupyterLite, which requires the dataset to be downloaded to the interface. While working on the downloaded version of this notebook on their local machines, the learners can simply **skip the steps above**, and simply use the URL directly in the `pandas.read_csv()` function. You can uncomment and run the statements in the cell below.

In [33]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"
df = pd.read_csv(filename)

We can use the method <code>head()</code> to examine the first five rows of a dataframe:

In [34]:
# Print first five rows of the dataframe

df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [41]:
# Read data from Excel File and print the first five rows

xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/jupyterlite/files/Module%205/data/TopSellingAlbums.xlsx'

#await download(xlsx_path, "TopSellingAlbums.xlsx")
#df = pd.read_excel("TopSellingAlbums.xlsx")
#df.head()

df = pd.read_excel(xlsx_path)
df.head()
#df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Artist                            8 non-null      object
 1   Album                             8 non-null      object
 2   Released                          8 non-null      int64
 3   Length                            8 non-null      object
 4   Genre                             8 non-null      object
 5   Music Recording Sales (millions)  8 non-null      float64
 6   Claimed Sales (millions)          8 non-null      int64
 7   Released.1                        8 non-null      datetime64[ns]
 8   Soundtrack                        2 non-null      object
 9   Rating                            8 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 772.0+ bytes

> Note: This version of the lab is working on JupyterLite, which requires the dataset to be downloaded to the interface. While working on the downloaded version of this notebook on their local machines, the learners can simply **skip the steps above**, and simply use the URL directly in the `pandas.read_excel()` function. You can uncomment and run the statements in the cell below.

In [42]:
xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/jupyterlite/files/Module%205/data/TopSellingAlbums.xlsx'
df = pd.read_excel(xlsx_path)
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

We can access the column <b>Length</b> and assign it a new dataframe <b>x</b>:

In [43]:
# Access to the column Length

x = df[['Length']]
x

     Length
0  00:42:19
1   0:42:11
2   0:42:49
3   0:57:44
4   0:46:33
5   0:43:08
6  01:15:54
7   0:40:01

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgOne.png" width="750">

<hr>

## Viewing Data and Accessing Data

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [46]:
# Get the column as a series

x = df['Length']
x

pandas.core.series.Series

You can also get a column as a dataframe. For example, we can assign the column <b>Artist</b>:

In [45]:
# Get the column as a dataframe

x = df[['Artist']]
type(x)

pandas.core.frame.DataFrame

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [47]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

            Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC   0:42:11                    hard rock
2       Pink Floyd   0:42:49             progressive rock
3  Whitney Houston   0:57:44               R&B, soul, pop
4        Meat Loaf   0:46:33  hard rock, progressive rock
5           Eagles   0:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac   0:40:01                    soft rock

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgTwo.png" width="1100">

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [58]:
# Access the value on the first row and the first column

df.iloc[0, 0]

'Michael Jackson'

You can access the 2nd row and the 1st column as follows:

In [59]:
# Access the value on the second row and the first column

df.iloc[1,0]

'AC/DC'

You can access the 1st row and the 3rd column as follows:

In [60]:
# Access the value on the first row and the third column

df.iloc[0,2]

np.int64(1982)

In [61]:
# Access the value on the second row and the third column
df.iloc[1,2]

np.int64(1980)

This is shown in the following image

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/2_loc.PNG" width="750">

You can access the column using the name as well, the following are the same as above:

In [62]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [63]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [64]:
# Access the column using the name

df.loc[0, 'Released']

np.int64(1982)

In [65]:
# Access the column using the name

df.loc[1, 'Released']

np.int64(1980)

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/1_loc.png" width="750">

You can perform slicing using both the index and the name of the column:

In [66]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/4_loc.png" width="750">

In [67]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released']

            Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/3_loc.png" width="750">

<hr>

## Quiz on DataFrame

Use a variable <code>q</code> to store the column <b>Rating</b> as a dataframe

In [69]:
# Write your code below and press Shift+Enter to execute
q = df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

<details><summary>Click here for the solution</summary>

```python
q = df[['Rating']]
q
    
```

</details>

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Released</b> and <b>Artist</b>:

In [75]:
# Write your code below and press Shift+Enter to execute
q = df[['Released', 'Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

<details><summary>Click here for the solution</summary>

```python
q = df[['Released', 'Artist']]
q
    
```

</details>

Access the 2nd row and the 3rd column of <code>df</code>:

In [77]:
# Write your code below and press Shift+Enter to execute
print(df.iloc[1, 2])

1980

<details><summary>Click here for the solution</summary>

```python
df.iloc[1, 2]
    
```

</details>

Use the following list to convert the dataframe index <code>df</code> to characters and assign it to <code>df_new</code>; find the element corresponding to the row index <code>a</code> and column  <code>'Artist'</code>. Then select the rows <code>a</code> through <code>d</code> for the column  <code>'Artist'</code>

In [81]:
new_index=['a','b','c','d','e','f','g','h']
df.index = new_index
df_new = df
#df_new
#df_new.loc['a', 'Artist']
#df_new.loc['a':'d', 'Artist']

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
a,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
b,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
c,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
d,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
e,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0
f,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,1976-02-17,NaN,7.5
g,Bee Gees,Saturday Night Fever,1977,01:15:54,disco,20.6,40,1977-11-15,Y,7.0
h,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,1977-02-04,NaN,6.5

<details><summary>Click here for the solution</summary>

```python
df_new=df
df_new.index=new_index
df_new.loc['a', 'Artist']
df_new.loc['a':'d', 'Artist']
    
```

</details>

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python.
<hr>

## Authors:

[Joseph Santarcangelo](https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01)

Joseph Santarcangelo has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>

<!--## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                 |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 2023-11-02 | 2.2 | Abhishek Gagneja | Instructions updated |
| 2022-01-10        | 2.1     | Malika     | Removed the readme for GitShare    |
| 2020-08-26        | 2.0     | Lavanya    | Moved lab to course repo in GitLab |
| 2020-11-24        | 3.0     | Nayef      | Added new images                   |
|                   |         |            |                                    |

<hr/>
--!>